repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9
      args: [--config, qgis/examples/quick_api_interactive_proper_testing/pyproject.toml]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4  # pick a git hash / tag to point to
  hooks:
    - id: flake8
      args: [--config, qgis/examples/quick_api_interactive_proper_testing/setup.cfg]
